import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./root.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alexander Rojas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer>Published with GitHubPages</footer>
      </body>
    </html>
  );
}
